In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [2]:
df = pd.read_csv('df_final.csv')
df.head()

,Timestamp,SPY Opening Price,QQQ Opening Price,VXX Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY 5D Avg Volume,...,QQQ 1D Stock Change,VXX 5D Stock Change,VXX 3D Stock Change,VXX 1D Stock Change,DIA 5D Stock Change,DIA 3D Stock Change,DIA 1D Stock Change,SPY Strike,SPY Open CC,SPY Close CC
0,2022-01-03,477.26,399.85,72.56,364.79,477.38,401.6800,71.76,365.24,55624228.0,...,0,-0.08,-0.04,0,0.01,0.00,0,478,-1.0,-1.0
1,2022-01-04,479.11,402.13,71.04,367.08,477.17,394.8700,71.48,368.26,58796150.8,...,0,-0.08,-0.04,0,0.00,0.00,0,480,-1.0,-1.0
2,2022-01-05,477.09,394.92,71.88,367.94,471.11,386.9400,74.90,365.38,63615369.4,...,0,-0.07,-0.04,0,0.00,0.00,0,478,-1.0,-1.0
3,2022-01-06,468.35,382.37,77.08,364.96,468.99,385.0000,76.48,362.84,73696064.6,...,0,0.01,0.03,0,0.00,0.00,0,469,-1.0,-1.0
4,2022-01-07,466.42,381.16,77.60,361.70,467.11,380.5707,75.48,363.34,79929956.4,...,0,0.02,0.08,0,0.00,-0.01,0,467,-1.0,-1.0

In [3]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df

,Timestamp,SPY Opening Price,QQQ Opening Price,VXX Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY 5D Avg Volume,...,QQQ 1D Stock Change,VXX 5D Stock Change,VXX 3D Stock Change,VXX 1D Stock Change,DIA 5D Stock Change,DIA 3D Stock Change,DIA 1D Stock Change,SPY Strike,SPY Open CC,SPY Close CC
0,2022-01-03,477.26,399.850,72.560,364.79,477.3800,401.6800,71.760,365.24,55624228.0,...,0,-0.08,-0.04,0,0.01,0.00,0,478,-1.00,-1.00
1,2022-01-04,479.11,402.130,71.040,367.08,477.1700,394.8700,71.480,368.26,58796150.8,...,0,-0.08,-0.04,0,0.00,0.00,0,480,-1.00,-1.00
2,2022-01-05,477.09,394.920,71.880,367.94,471.1100,386.9400,74.900,365.38,63615369.4,...,0,-0.07,-0.04,0,0.00,0.00,0,478,-1.00,-1.00
3,2022-01-06,468.35,382.370,77.080,364.96,468.9900,385.0000,76.480,362.84,73696064.6,...,0,0.01,0.03,0,0.00,0.00,0,469,-1.00,-1.00
4,2022-01-07,466.42,381.160,77.600,361.70,467.1100,380.5707,75.480,363.34,79929956.4,...,0,0.02,0.08,0,0.00,-0.01,0,467,-1.00,-1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,441.165,13.390,391.65,512.7450,437.0000,14.100,388.46,67140546.0,...,0,-0.03,-0.07,0,0.01,0.01,0,517,0.87,0.01
492,2024-03-15,510.19,435.020,13.982,388.19,509.4451,434.0599,14.100,386.64,77442633.0,...,0,0.01,0.01,0,0.00,0.00,0,511,0.93,0.11
493,2024-03-18,514.26,439.480,13.880,387.72,513.6400,438.5250,13.750,388.17,81665385.4,...,0,-0.03,0.04,0,-0.00,-0.01,0,515,0.86,0.16
494,2024-03-19,511.27,433.914,13.850,387.72,515.0200,438.0500,13.510,390.56,86959112.2,...,0,-0.02,-0.02,0,0.00,-0.00,0,512,0.74,3.63
495,2024-03-20,515.22,438.610,13.450,390.20,519.1700,442.8400,13.162,394.31,84536277.0,...,0,-0.00,-0.03,0,-0.00,0.01,0,516,1.43,3.83

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            496 non-null    datetime64[ns]
 1   SPY Opening Price    496 non-null    float64
 2   QQQ Opening Price    496 non-null    float64
 3   VXX Opening Price    496 non-null    float64
 4   DIA Opening Price    496 non-null    float64
 5   SPY Closing Price    496 non-null    float64
 6   QQQ Closing Price    496 non-null    float64
 7   VXX Closing Price    496 non-null    float64
 8   DIA Closing Price    496 non-null    float64
 9   SPY 5D Avg Volume    496 non-null    float64
 10  SPY 3D Avg Volume    496 non-null    float64
 11  SPY 1D Avg Volume    496 non-null    float64
 12  QQQ 5D Avg Volume    496 non-null    float64
 13  QQQ 3D Avg Volume    496 non-null    float64
 14  QQQ 1D Avg Volume    496 non-null    float64
 15  VXX 5D Avg Volume    496 non-null    float64
 16  VXX 3D Avg Volume    496 non-null    float64
 17  VXX 1D Avg Volume    496 non-null    float64
 18  DIA 5D Avg Volume    496 non-null    float64
 19  DIA 3D Avg Volume    496 non-null    float64
 20  DIA 1D Avg Volume    496 non-null    float64
 21  SPY 5D Stock Change  496 non-null    float64
 22  SPY 3D Stock Change  496 non-null    float64
 23  SPY 1D Stock Change  496 non-null    int64
 24  QQQ 5D Stock Change  496 non-null    float64
 25  QQQ 3D Stock Change  496 non-null    float64
 26  QQQ 1D Stock Change  496 non-null    int64
 27  VXX 5D Stock Change  496 non-null    float64
 28  VXX 3D Stock Change  496 non-null    float64
 29  VXX 1D Stock Change  496 non-null    int64
 30  DIA 5D Stock Change  496 non-null    float64
 31  DIA 3D Stock Change  496 non-null    float64
 32  DIA 1D Stock Change  496 non-null    int64
 33  SPY Strike           496 non-null    int64
 34  SPY Open CC          496 non-null    float64
 35  SPY Close CC         496 non-null    float64
dtypes: datetime64[ns](1), float64(30), int64(5)
memory usage: 139.6 KB

In [5]:
df['Todays_SPY_change'] = df['SPY Closing Price'] - df['SPY Opening Price']

In [6]:
df = df[['Timestamp' , 'SPY Opening Price' , 'VXX Opening Price' , 'QQQ Opening Price' ,\
        'DIA Opening Price' , 'SPY Closing Price' , 'QQQ Closing Price' , 'VXX Closing Price' , \
       'DIA Closing Price' , 'SPY Strike' , 'SPY Open CC' , 'SPY Close CC' , 'Todays_SPY_change']]
df

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change
0,2022-01-03,477.26,72.560,399.850,364.79,477.3800,401.6800,71.760,365.24,478,-1.00,-1.00,0.1200
1,2022-01-04,479.11,71.040,402.130,367.08,477.1700,394.8700,71.480,368.26,480,-1.00,-1.00,-1.9400
2,2022-01-05,477.09,71.880,394.920,367.94,471.1100,386.9400,74.900,365.38,478,-1.00,-1.00,-5.9800
3,2022-01-06,468.35,77.080,382.370,364.96,468.9900,385.0000,76.480,362.84,469,-1.00,-1.00,0.6400
4,2022-01-07,466.42,77.600,381.160,361.70,467.1100,380.5707,75.480,363.34,467,-1.00,-1.00,0.6900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,512.7450,437.0000,14.100,388.46,517,0.87,0.01,-3.8950
492,2024-03-15,510.19,13.982,435.020,388.19,509.4451,434.0599,14.100,386.64,511,0.93,0.11,-0.7449
493,2024-03-18,514.26,13.880,439.480,387.72,513.6400,438.5250,13.750,388.17,515,0.86,0.16,-0.6200
494,2024-03-19,511.27,13.850,433.914,387.72,515.0200,438.0500,13.510,390.56,512,0.74,3.63,3.7500
495,2024-03-20,515.22,13.450,438.610,390.20,519.1700,442.8400,13.162,394.31,516,1.43,3.83,3.9500

In [7]:
# Trim the data file so that we have the covered call prices. The API will only go back 2 years.
#start_date = '2022-04-06'
#end_date = '2024-03-20'
df = df[(df['Timestamp'] >= '2022-04-06') & (df['Timestamp'] <= '2024-03-20')]
df

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change
59,2022-04-06,446.12,104.460,354.810,343.34,446.5500,353.7000,97.400,344.73,447,1.24,1.21,0.4300
60,2022-04-07,446.02,96.720,353.660,343.34,449.6000,355.0900,96.200,346.39,447,0.00,0.00,3.5800
61,2022-04-08,447.07,96.680,350.260,345.65,447.7700,349.2800,98.480,347.51,448,0.95,1.02,0.7000
62,2022-04-11,443.24,99.000,343.560,345.64,440.0000,341.0000,101.840,343.22,444,1.06,0.02,-3.2400
63,2022-04-12,442.40,100.080,343.685,344.32,437.3700,338.9400,102.200,341.59,443,0.00,0.00,-5.0300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,512.7450,437.0000,14.100,388.46,517,0.87,0.01,-3.8950
492,2024-03-15,510.19,13.982,435.020,388.19,509.4451,434.0599,14.100,386.64,511,0.93,0.11,-0.7449
493,2024-03-18,514.26,13.880,439.480,387.72,513.6400,438.5250,13.750,388.17,515,0.86,0.16,-0.6200
494,2024-03-19,511.27,13.850,433.914,387.72,515.0200,438.0500,13.510,390.56,512,0.74,3.63,3.7500
495,2024-03-20,515.22,13.450,438.610,390.20,519.1700,442.8400,13.162,394.31,516,1.43,3.83,3.9500

In [8]:
# Need to correct the SPY CC closing price
# Iterate over rows
for index, row in df.iterrows():
    if row['SPY Closing Price'] > row['SPY Strike'] and row['SPY Open CC'] > 0:
        df.at[index, 'SPY Close CC'] = row['SPY Closing Price'] - row['SPY Strike']
    else:
        df.at[index, 'SPY Close CC'] = 0
    
df

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change
59,2022-04-06,446.12,104.460,354.810,343.34,446.5500,353.7000,97.400,344.73,447,1.24,0.00,0.4300
60,2022-04-07,446.02,96.720,353.660,343.34,449.6000,355.0900,96.200,346.39,447,0.00,0.00,3.5800
61,2022-04-08,447.07,96.680,350.260,345.65,447.7700,349.2800,98.480,347.51,448,0.95,0.00,0.7000
62,2022-04-11,443.24,99.000,343.560,345.64,440.0000,341.0000,101.840,343.22,444,1.06,0.00,-3.2400
63,2022-04-12,442.40,100.080,343.685,344.32,437.3700,338.9400,102.200,341.59,443,0.00,0.00,-5.0300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,512.7450,437.0000,14.100,388.46,517,0.87,0.00,-3.8950
492,2024-03-15,510.19,13.982,435.020,388.19,509.4451,434.0599,14.100,386.64,511,0.93,0.00,-0.7449
493,2024-03-18,514.26,13.880,439.480,387.72,513.6400,438.5250,13.750,388.17,515,0.86,0.00,-0.6200
494,2024-03-19,511.27,13.850,433.914,387.72,515.0200,438.0500,13.510,390.56,512,0.74,3.02,3.7500
495,2024-03-20,515.22,13.450,438.610,390.20,519.1700,442.8400,13.162,394.31,516,1.43,3.17,3.9500

In [9]:
# Adding a column that has day of week - Monday, Tuesday, etc.
# Need this to show that we can "fix" the data
# df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['day_of_week'] = df['Timestamp'].dt.day_name()  
df

/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3641201071.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day_of_week'] = df['Timestamp'].dt.day_name()

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change,day_of_week
59,2022-04-06,446.12,104.460,354.810,343.34,446.5500,353.7000,97.400,344.73,447,1.24,0.00,0.4300,Wednesday
60,2022-04-07,446.02,96.720,353.660,343.34,449.6000,355.0900,96.200,346.39,447,0.00,0.00,3.5800,Thursday
61,2022-04-08,447.07,96.680,350.260,345.65,447.7700,349.2800,98.480,347.51,448,0.95,0.00,0.7000,Friday
62,2022-04-11,443.24,99.000,343.560,345.64,440.0000,341.0000,101.840,343.22,444,1.06,0.00,-3.2400,Monday
63,2022-04-12,442.40,100.080,343.685,344.32,437.3700,338.9400,102.200,341.59,443,0.00,0.00,-5.0300,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,512.7450,437.0000,14.100,388.46,517,0.87,0.00,-3.8950,Thursday
492,2024-03-15,510.19,13.982,435.020,388.19,509.4451,434.0599,14.100,386.64,511,0.93,0.00,-0.7449,Friday
493,2024-03-18,514.26,13.880,439.480,387.72,513.6400,438.5250,13.750,388.17,515,0.86,0.00,-0.6200,Monday
494,2024-03-19,511.27,13.850,433.914,387.72,515.0200,438.0500,13.510,390.56,512,0.74,3.02,3.7500,Tuesday
495,2024-03-20,515.22,13.450,438.610,390.20,519.1700,442.8400,13.162,394.31,516,1.43,3.17,3.9500,Wednesday

In [10]:
df['net_gain'] = df['SPY Closing Price'] - df['SPY Opening Price'] + df['SPY Open CC'] - df['SPY Close CC']
df

/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3827066245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['net_gain'] = df['SPY Closing Price'] - df['SPY Opening Price'] + df['SPY Open CC'] - df['SPY Close CC']

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change,day_of_week,net_gain
59,2022-04-06,446.12,104.460,354.810,343.34,446.5500,353.7000,97.400,344.73,447,1.24,0.00,0.4300,Wednesday,1.6700
60,2022-04-07,446.02,96.720,353.660,343.34,449.6000,355.0900,96.200,346.39,447,0.00,0.00,3.5800,Thursday,3.5800
61,2022-04-08,447.07,96.680,350.260,345.65,447.7700,349.2800,98.480,347.51,448,0.95,0.00,0.7000,Friday,1.6500
62,2022-04-11,443.24,99.000,343.560,345.64,440.0000,341.0000,101.840,343.22,444,1.06,0.00,-3.2400,Monday,-2.1800
63,2022-04-12,442.40,100.080,343.685,344.32,437.3700,338.9400,102.200,341.59,443,0.00,0.00,-5.0300,Tuesday,-5.0300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,512.7450,437.0000,14.100,388.46,517,0.87,0.00,-3.8950,Thursday,-3.0250
492,2024-03-15,510.19,13.982,435.020,388.19,509.4451,434.0599,14.100,386.64,511,0.93,0.00,-0.7449,Friday,0.1851
493,2024-03-18,514.26,13.880,439.480,387.72,513.6400,438.5250,13.750,388.17,515,0.86,0.00,-0.6200,Monday,0.2400
494,2024-03-19,511.27,13.850,433.914,387.72,515.0200,438.0500,13.510,390.56,512,0.74,3.02,3.7500,Tuesday,1.4700
495,2024-03-20,515.22,13.450,438.610,390.20,519.1700,442.8400,13.162,394.31,516,1.43,3.17,3.9500,Wednesday,2.2100

In [11]:
df['net_gain'].sum()

107.52049999999937

In [12]:
CC_gain = df['SPY Open CC'].sum() - df['SPY Close CC'].sum()
CC_gain

14.904299999999978

In [13]:
# Create a bear market data file named df_bear
start_date = '2022-01-03'
end_date = '2022-10-07'
df_bear = df[(df['Timestamp'] >= start_date) & (df['Timestamp'] <= end_date)]
df_bear

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change,day_of_week,net_gain
59,2022-04-06,446.12,104.46,354.810,343.3400,446.55,353.7000,97.40,344.73,447,1.24,0.00,0.43,Wednesday,1.67
60,2022-04-07,446.02,96.72,353.660,343.3400,449.60,355.0900,96.20,346.39,447,0.00,0.00,3.58,Thursday,3.58
61,2022-04-08,447.07,96.68,350.260,345.6500,447.77,349.2800,98.48,347.51,448,0.95,0.00,0.70,Friday,1.65
62,2022-04-11,443.24,99.00,343.560,345.6400,440.00,341.0000,101.84,343.22,444,1.06,0.00,-3.24,Monday,-2.18
63,2022-04-12,442.40,100.08,343.685,344.3200,437.37,338.9400,102.20,341.59,443,0.00,0.00,-5.03,Tuesday,-5.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2022-10-03,359.67,82.12,267.980,289.6700,366.90,274.0200,80.26,295.09,360,1.68,6.90,7.23,Monday,2.01
183,2022-10-04,373.47,76.92,279.620,299.4200,376.59,281.1500,77.84,302.23,374,0.00,0.00,3.12,Tuesday,3.12
184,2022-10-05,373.77,78.42,278.200,300.2400,377.88,282.7200,77.96,303.44,374,1.60,3.88,4.11,Wednesday,1.83
185,2022-10-06,376.16,77.16,282.170,301.5500,373.46,279.9000,80.16,299.36,377,0.00,0.00,-2.70,Thursday,-2.70
186,2022-10-07,367.87,81.30,274.170,295.7253,361.99,268.4301,83.52,292.38,368,1.41,0.00,-5.88,Friday,-4.47

In [14]:
df_bear['net_gain'].sum()

5.718599999999796

In [15]:
# Create a bull market data file named df_bull
start_date = '2022-10-07'
end_date = '2024-03-20'
df_bull = df[(df['Timestamp'] >= start_date) & (df['Timestamp'] <= end_date)]
df_bull

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change,day_of_week,net_gain
186,2022-10-07,367.87,81.300,274.170,295.7253,361.9900,268.4301,83.520,292.38,368,1.41,0.00,-5.8800,Friday,-4.4700
187,2022-10-10,362.49,84.600,267.200,293.9800,360.7024,266.7500,84.780,292.65,363,1.47,0.00,-1.7876,Monday,-0.3176
188,2022-10-11,357.21,86.400,263.540,290.9600,357.0800,262.2900,86.320,292.28,358,0.00,0.00,-0.1300,Tuesday,-0.1300
189,2022-10-12,356.86,86.160,262.500,291.7500,357.4700,263.2000,85.520,292.88,357,2.61,0.47,0.6100,Wednesday,2.7500
190,2022-10-13,348.53,87.040,254.480,286.7600,365.8100,268.7300,83.760,300.44,349,0.00,0.00,17.2800,Thursday,17.2800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.6500,512.7450,437.0000,14.100,388.46,517,0.87,0.00,-3.8950,Thursday,-3.0250
492,2024-03-15,510.19,13.982,435.020,388.1900,509.4451,434.0599,14.100,386.64,511,0.93,0.00,-0.7449,Friday,0.1851
493,2024-03-18,514.26,13.880,439.480,387.7200,513.6400,438.5250,13.750,388.17,515,0.86,0.00,-0.6200,Monday,0.2400
494,2024-03-19,511.27,13.850,433.914,387.7200,515.0200,438.0500,13.510,390.56,512,0.74,3.02,3.7500,Tuesday,1.4700
495,2024-03-20,515.22,13.450,438.610,390.2000,519.1700,442.8400,13.162,394.31,516,1.43,3.17,3.9500,Wednesday,2.2100

In [16]:
df_bull['net_gain'].sum()

97.33189999999959

In [17]:
df['SPY Closing Price'] = df['SPY Closing Price'].shift(1)
df['QQQ Closing Price'] = df['QQQ Closing Price'].shift(1)
df['VXX Closing Price'] = df['VXX Closing Price'].shift(1)
df['DIA Closing Price'] = df['DIA Closing Price'].shift(1)
df

/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3191503497.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SPY Closing Price'] = df['SPY Closing Price'].shift(1)
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3191503497.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QQQ Closing Price'] = df['QQQ Closing Price'].shift(1)
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3191503497.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VXX Closing Price'] = df['VXX Closing Price'].shift(1)
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/3191503497.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIA Closing Price'] = df['DIA Closing Price'].shift(1)

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,SPY Open CC,SPY Close CC,Todays_SPY_change,day_of_week,net_gain
59,2022-04-06,446.12,104.460,354.810,343.34,NaN,NaN,NaN,NaN,447,1.24,0.00,0.4300,Wednesday,1.6700
60,2022-04-07,446.02,96.720,353.660,343.34,446.5500,353.7000,97.4000,344.73,447,0.00,0.00,3.5800,Thursday,3.5800
61,2022-04-08,447.07,96.680,350.260,345.65,449.6000,355.0900,96.2000,346.39,448,0.95,0.00,0.7000,Friday,1.6500
62,2022-04-11,443.24,99.000,343.560,345.64,447.7700,349.2800,98.4800,347.51,444,1.06,0.00,-3.2400,Monday,-2.1800
63,2022-04-12,442.40,100.080,343.685,344.32,440.0000,341.0000,101.8400,343.22,443,0.00,0.00,-5.0300,Tuesday,-5.0300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,515.7100,439.9700,13.5703,391.11,517,0.87,0.00,-3.8950,Thursday,-3.0250
492,2024-03-15,510.19,13.982,435.020,388.19,512.7450,437.0000,14.1000,388.46,511,0.93,0.00,-0.7449,Friday,0.1851
493,2024-03-18,514.26,13.880,439.480,387.72,509.4451,434.0599,14.1000,386.64,515,0.86,0.00,-0.6200,Monday,0.2400
494,2024-03-19,511.27,13.850,433.914,387.72,513.6400,438.5250,13.7500,388.17,512,0.74,3.02,3.7500,Tuesday,1.4700
495,2024-03-20,515.22,13.450,438.610,390.20,515.0200,438.0500,13.5100,390.56,516,1.43,3.17,3.9500,Wednesday,2.2100

In [18]:

df['SPY_5d_change'] = df['SPY Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['SPY_3d_change'] = df['SPY Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['SPY_1d_change'] = df['SPY Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['VXX_5d_change'] = df['VXX Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['VXX_3d_change'] = df['VXX Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['VXX_1d_change'] = df['VXX Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['QQQ_5d_change'] = df['QQQ Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['QQQ_3d_change'] = df['QQQ Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['QQQ_1d_change'] = df['QQQ Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['DIA_5d_change'] = df['DIA Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['DIA_3d_change'] = df['DIA Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
df['DIA_1d_change'] = df['DIA Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
df

/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SPY_5d_change'] = df['SPY Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SPY_3d_change'] = df['SPY Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SPY_1d_change'] = df['SPY Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VXX_5d_change'] = df['VXX Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VXX_3d_change'] = df['VXX Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VXX_1d_change'] = df['VXX Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QQQ_5d_change'] = df['QQQ Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QQQ_3d_change'] = df['QQQ Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['QQQ_1d_change'] = df['QQQ Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIA_5d_change'] = df['DIA Opening Price'].rolling(window=6, min_periods=6).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIA_3d_change'] = df['DIA Opening Price'].rolling(window=4, min_periods=4).apply(lambda x: x.iloc[-1] - x.iloc[0])
/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/4190126921.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DIA_1d_change'] = df['DIA Opening Price'].rolling(window=2, min_periods=2).apply(lambda x: x.iloc[-1] - x.iloc[0])

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,...,SPY_1d_change,VXX_5d_change,VXX_3d_change,VXX_1d_change,QQQ_5d_change,QQQ_3d_change,QQQ_1d_change,DIA_5d_change,DIA_3d_change,DIA_1d_change
59,2022-04-06,446.12,104.460,354.810,343.34,NaN,NaN,NaN,NaN,447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,2022-04-07,446.02,96.720,353.660,343.34,446.5500,353.7000,97.4000,344.73,447,...,-0.10,NaN,NaN,-7.740,NaN,NaN,-1.150,NaN,NaN,0.00
61,2022-04-08,447.07,96.680,350.260,345.65,449.6000,355.0900,96.2000,346.39,448,...,1.05,NaN,NaN,-0.040,NaN,NaN,-3.400,NaN,NaN,2.31
62,2022-04-11,443.24,99.000,343.560,345.64,447.7700,349.2800,98.4800,347.51,444,...,-3.83,NaN,-5.460,2.320,NaN,-11.250,-6.700,NaN,2.300,-0.01
63,2022-04-12,442.40,100.080,343.685,344.32,440.0000,341.0000,101.8400,343.22,443,...,-0.84,NaN,3.360,1.080,NaN,-9.975,0.125,NaN,0.980,-1.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,515.7100,439.9700,13.5703,391.11,517,...,0.21,-0.590,-1.190,-0.150,-0.355,5.315,-0.275,3.370,4.765,0.67
492,2024-03-15,510.19,13.982,435.020,388.19,512.7450,437.0000,14.1000,388.46,511,...,-6.45,0.082,0.022,0.592,-10.380,-2.580,-6.145,0.110,0.250,-3.46
493,2024-03-18,514.26,13.880,439.480,387.72,509.4451,434.0599,14.1000,386.64,515,...,4.07,-0.700,0.340,-0.102,3.630,-1.960,4.460,0.835,-3.260,-0.47
494,2024-03-19,511.27,13.850,433.914,387.72,513.6400,438.5250,13.7500,388.17,512,...,-2.99,-0.110,0.460,-0.030,-3.686,-7.251,-5.566,-0.220,-3.930,0.00
495,2024-03-20,515.22,13.450,438.610,390.20,515.0200,438.0500,13.5100,390.56,516,...,3.95,-0.090,-0.532,-0.400,-2.830,3.590,4.696,-0.780,2.010,2.48

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 437 entries, 59 to 495
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Timestamp          437 non-null    datetime64[ns]
 1   SPY Opening Price  437 non-null    float64
 2   VXX Opening Price  437 non-null    float64
 3   QQQ Opening Price  437 non-null    float64
 4   DIA Opening Price  437 non-null    float64
 5   SPY Closing Price  436 non-null    float64
 6   QQQ Closing Price  436 non-null    float64
 7   VXX Closing Price  436 non-null    float64
 8   DIA Closing Price  436 non-null    float64
 9   SPY Strike         437 non-null    int64
 10  SPY Open CC        437 non-null    float64
 11  SPY Close CC       437 non-null    float64
 12  Todays_SPY_change  437 non-null    float64
 13  day_of_week        437 non-null    object
 14  net_gain           437 non-null    float64
 15  SPY_5d_change      432 non-null    float64
 16  SPY_3d_change      434 non-null    float64
 17  SPY_1d_change      436 non-null    float64
 18  VXX_5d_change      432 non-null    float64
 19  VXX_3d_change      434 non-null    float64
 20  VXX_1d_change      436 non-null    float64
 21  QQQ_5d_change      432 non-null    float64
 22  QQQ_3d_change      434 non-null    float64
 23  QQQ_1d_change      436 non-null    float64
 24  DIA_5d_change      432 non-null    float64
 25  DIA_3d_change      434 non-null    float64
 26  DIA_1d_change      436 non-null    float64
dtypes: datetime64[ns](1), float64(24), int64(1), object(1)
memory usage: 111.8+ KB

In [20]:
print(df.columns)

Index(['Timestamp', 'SPY Opening Price', 'VXX Opening Price',
       'QQQ Opening Price', 'DIA Opening Price', 'SPY Closing Price',
       'QQQ Closing Price', 'VXX Closing Price', 'DIA Closing Price',
       'SPY Strike', 'SPY Open CC', 'SPY Close CC', 'Todays_SPY_change',
       'day_of_week', 'net_gain', 'SPY_5d_change', 'SPY_3d_change',
       'SPY_1d_change', 'VXX_5d_change', 'VXX_3d_change', 'VXX_1d_change',
       'QQQ_5d_change', 'QQQ_3d_change', 'QQQ_1d_change', 'DIA_5d_change',
       'DIA_3d_change', 'DIA_1d_change'],
      dtype='object')

In [21]:
df.drop(columns=['net_gain'], inplace=True)
# df.drop(index='index_label', inplace=True)
df

/var/folders/2s/f93p50997jv25r58r7_glvy00000gn/T/ipykernel_88162/2636525793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['net_gain'], inplace=True)

,Timestamp,SPY Opening Price,VXX Opening Price,QQQ Opening Price,DIA Opening Price,SPY Closing Price,QQQ Closing Price,VXX Closing Price,DIA Closing Price,SPY Strike,...,SPY_1d_change,VXX_5d_change,VXX_3d_change,VXX_1d_change,QQQ_5d_change,QQQ_3d_change,QQQ_1d_change,DIA_5d_change,DIA_3d_change,DIA_1d_change
59,2022-04-06,446.12,104.460,354.810,343.34,NaN,NaN,NaN,NaN,447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,2022-04-07,446.02,96.720,353.660,343.34,446.5500,353.7000,97.4000,344.73,447,...,-0.10,NaN,NaN,-7.740,NaN,NaN,-1.150,NaN,NaN,0.00
61,2022-04-08,447.07,96.680,350.260,345.65,449.6000,355.0900,96.2000,346.39,448,...,1.05,NaN,NaN,-0.040,NaN,NaN,-3.400,NaN,NaN,2.31
62,2022-04-11,443.24,99.000,343.560,345.64,447.7700,349.2800,98.4800,347.51,444,...,-3.83,NaN,-5.460,2.320,NaN,-11.250,-6.700,NaN,2.300,-0.01
63,2022-04-12,442.40,100.080,343.685,344.32,440.0000,341.0000,101.8400,343.22,443,...,-0.84,NaN,3.360,1.080,NaN,-9.975,0.125,NaN,0.980,-1.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,2024-03-14,516.64,13.390,441.165,391.65,515.7100,439.9700,13.5703,391.11,517,...,0.21,-0.590,-1.190,-0.150,-0.355,5.315,-0.275,3.370,4.765,0.67
492,2024-03-15,510.19,13.982,435.020,388.19,512.7450,437.0000,14.1000,388.46,511,...,-6.45,0.082,0.022,0.592,-10.380,-2.580,-6.145,0.110,0.250,-3.46
493,2024-03-18,514.26,13.880,439.480,387.72,509.4451,434.0599,14.1000,386.64,515,...,4.07,-0.700,0.340,-0.102,3.630,-1.960,4.460,0.835,-3.260,-0.47
494,2024-03-19,511.27,13.850,433.914,387.72,513.6400,438.5250,13.7500,388.17,512,...,-2.99,-0.110,0.460,-0.030,-3.686,-7.251,-5.566,-0.220,-3.930,0.00
495,2024-03-20,515.22,13.450,438.610,390.20,515.0200,438.0500,13.5100,390.56,516,...,3.95,-0.090,-0.532,-0.400,-2.830,3.590,4.696,-0.780,2.010,2.48

In [22]:
print(df.columns)

Index(['Timestamp', 'SPY Opening Price', 'VXX Opening Price',
       'QQQ Opening Price', 'DIA Opening Price', 'SPY Closing Price',
       'QQQ Closing Price', 'VXX Closing Price', 'DIA Closing Price',
       'SPY Strike', 'SPY Open CC', 'SPY Close CC', 'Todays_SPY_change',
       'day_of_week', 'SPY_5d_change', 'SPY_3d_change', 'SPY_1d_change',
       'VXX_5d_change', 'VXX_3d_change', 'VXX_1d_change', 'QQQ_5d_change',
       'QQQ_3d_change', 'QQQ_1d_change', 'DIA_5d_change', 'DIA_3d_change',
       'DIA_1d_change'],
      dtype='object')

In [ ]:
# the y value is 'Todays_SPY_Change'